Pdm_TEI49_Fonct:
  4.2f_flowA:
    min: 9999.0
  4.2f_flowB":
    min: 99999.0
  6d_cellAInt":
    min: 80000
  6d_cellBInt":
    min: 80000
Pdm_TEI48_Fonct:
  6.4f_ratio:
    min: 1.1
    max: 1.2
  6.0f_agci:
    min: 190000
    max: 210000
  5.2f_flow:
    min: 1.0
  6.1f_biasvoltage:
    min: -110.0
    max: -120.0
Pdm_TEI48_Zero:
  5d_moy:
    max: 20
  5.1f_ect":
    max: 50